Bug with binding implicitly unwarapped optional (Xcode 8.3, Swift 3.1 support)
ApplauseOSS/Swifjection pull request #42
Opened 2017-04-10 15:43 UTC by azubala

What's up:
- changed object type to `Any?` in object binding to avoid issues with implicitly unwrapped optional
- added specs for binding implicitly unwrapped optional
- updated Cocoapods
- bumped version to `0.7.0`
- Updated `CHANGELOG`

2017-04-10 16:15 UTC, Przytua requested changes
Good one 👍 Just 2 remarks

2017-04-10 16:15 UTC, Przytua commented on CHANGELOG.md
> +### Changed:
Please change to '### Fixed:'

2017-04-10 16:15 UTC, Przytua commented on Sources/Swifjection/Classes/Bindings/Bindings.swift
> +    public func bind(object: Any?, toType type: Any.Type) {
Please add check if 'object' is not nil, otherwise there's no point in adding binding.

2017-04-10 17:18 UTC, azubala commented
@Przytua ready for the review.

2017-04-11 08:55 UTC, Przytua approved these changes
👍

2017-04-11 08:55 UTC, merged